/**
 * Application Constants
 */

const ROLES = {
  SUPER_ADMIN: "super_admin",
  USER: "user",
};

const LOG_ACTIONS = {
  // Authentication
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  LOGIN_FAILED: "LOGIN_FAILED",
  TOKEN_REFRESH: "TOKEN_REFRESH",

  // User Management
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_USER: "VIEW_USER",
  LIST_USERS: "LIST_USERS",
  SEARCH_USERS: "SEARCH_USERS",
  VIEW_USER_STATS: "VIEW_USER_STATS",

  // Oracle Instance Management
  CREATE_ORACLE_INSTANCE: "CREATE_ORACLE_INSTANCE",
  UPDATE_ORACLE_INSTANCE: "UPDATE_ORACLE_INSTANCE",
  DELETE_ORACLE_INSTANCE: "DELETE_ORACLE_INSTANCE",
  VIEW_ORACLE_INSTANCE: "VIEW_ORACLE_INSTANCE",
  LIST_ORACLE_INSTANCES: "LIST_ORACLE_INSTANCES",

  // Assignment
  ASSIGN_INSTANCE: "ASSIGN_INSTANCE",
  UNASSIGN_INSTANCE: "UNASSIGN_INSTANCE",

  // Generic CRUD (used by customer, assignment and other controllers)
  CREATE: "CREATE",
  VIEW:   "VIEW",
  UPDATE: "UPDATE",
  DELETE: "DELETE",

  // Config Copy
  CREATE_CONFIG_COPY:   "CREATE_CONFIG_COPY",
  VIEW_CONFIG_COPY:     "VIEW_CONFIG_COPY",
  LIST_CONFIG_COPIES:   "LIST_CONFIG_COPIES",
  DELETE_CONFIG_COPY:   "DELETE_CONFIG_COPY",
  RETRY_CONFIG_COPY:    "RETRY_CONFIG_COPY",
  ROLLBACK_CONFIG_COPY: "ROLLBACK_CONFIG_COPY",

  // System
  SYSTEM_ERROR: "SYSTEM_ERROR",
  API_ERROR: "API_ERROR",
};

const LOG_STATUS = {
  SUCCESS: "success",
  FAILURE: "failure",
  CRITICAL: "critical",
  INFO: "info",
};

const ENTITY_TYPES = {
  USER: "user",
  ORACLE_INSTANCE: "oracle_instance",
  ASSIGNMENT: "assignment",
  CONFIG_COPY_JOB: "config_copy_job",
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
};

module.exports = {
  ROLES,
  LOG_ACTIONS,
  LOG_STATUS,
  ENTITY_TYPES,
  HTTP_STATUS,
};
